// <auto-generated />
using System;
using BuscaImovel.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuscaImovel.Api.Data.Migrations
{
    [DbContext(typeof(BuscaImovelDbContext))]
    [Migration("20260527003100_AddPropertyExternalMetadata")]
    partial class AddPropertyExternalMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.19");

            modelBuilder.Entity("BuscaImovel.Api.Entities.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Area")
                        .HasColumnType("TEXT");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CondoFee")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Iptu")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFurnished")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPetFriendly")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ParkingSpaces")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceName", "ExternalId");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("655aae35-a729-4d5d-aeb2-5b1e91292cbd"),
                            Address = "Avenida Ibirapuera, 1234",
                            Area = 68m,
                            Bathrooms = 2,
                            Bedrooms = 2,
                            City = "São Paulo",
                            CondoFee = 950m,
                            CreatedAt = new DateTime(2026, 5, 27, 0, 30, 59, 508, DateTimeKind.Utc).AddTicks(6111),
                            Description = "Apartamento 2 dormitórios, mobiliado, composto por sala integrada, cozinha americana e varanda.",
                            ExternalId = "seed-001",
                            ImageUrl = "https://example.com/images/moema.jpg",
                            Iptu = 180m,
                            IsActive = true,
                            IsFurnished = true,
                            IsPetFriendly = true,
                            LastSeenAt = new DateTime(2026, 5, 27, 0, 30, 59, 508, DateTimeKind.Utc).AddTicks(6107),
                            Neighborhood = "Moema",
                            ParkingSpaces = 1,
                            Price = 5200m,
                            PropertyType = "Apartment",
                            SourceName = "QuintoAndar",
                            SourceUrl = "https://www.quintoandar.com.br/imovel/moema",
                            Title = "Apartamento mobiliado em Moema",
                            TransactionType = "Rent"
                        },
                        new
                        {
                            Id = new Guid("d49fc4b9-896a-4b4c-aa54-20fe1eb690fc"),
                            Address = "Rua Sena Madureira, 987",
                            Area = 150m,
                            Bathrooms = 3,
                            Bedrooms = 3,
                            City = "São Paulo",
                            CondoFee = 0m,
                            CreatedAt = new DateTime(2026, 5, 27, 0, 30, 59, 508, DateTimeKind.Utc).AddTicks(6121),
                            Description = "Casa térrea com 3 quartos, quintal e área gourmet próxima ao metrô.",
                            ExternalId = "seed-002",
                            ImageUrl = "https://example.com/images/vila-mariana.jpg",
                            Iptu = 120m,
                            IsActive = true,
                            IsFurnished = false,
                            IsPetFriendly = true,
                            LastSeenAt = new DateTime(2026, 5, 27, 0, 30, 59, 508, DateTimeKind.Utc).AddTicks(6120),
                            Neighborhood = "Vila Mariana",
                            ParkingSpaces = 2,
                            Price = 1450000m,
                            PropertyType = "House",
                            SourceName = "Zap Imóveis",
                            SourceUrl = "https://www.zapimoveis.com.br/imovel/vila-mariana",
                            Title = "House com quintal em Vila Mariana",
                            TransactionType = "Sale"
                        },
                        new
                        {
                            Id = new Guid("65fb3089-8185-4df1-9474-cfd926fb046e"),
                            Address = "Av. Cruzeiro do Sul, 3450",
                            Area = 32m,
                            Bathrooms = 1,
                            Bedrooms = 0,
                            City = "São Paulo",
                            CondoFee = 420m,
                            CreatedAt = new DateTime(2026, 5, 27, 0, 30, 59, 508, DateTimeKind.Utc).AddTicks(6130),
                            Description = "Studio compacto com área de serviço, ideal para estudante ou jovem profissional.",
                            ExternalId = "seed-003",
                            ImageUrl = "https://example.com/images/santana.jpg",
                            Iptu = 90m,
                            IsActive = true,
                            IsFurnished = true,
                            IsPetFriendly = false,
                            LastSeenAt = new DateTime(2026, 5, 27, 0, 30, 59, 508, DateTimeKind.Utc).AddTicks(6128),
                            Neighborhood = "Santana",
                            ParkingSpaces = 0,
                            Price = 2200m,
                            PropertyType = "Studio",
                            SourceName = "OLX",
                            SourceUrl = "https://www.olx.com.br/imovel/santana",
                            Title = "Studio moderno em Santana",
                            TransactionType = "Rent"
                        },
                        new
                        {
                            Id = new Guid("08c3e6e9-b04f-4a22-af24-8f62559bbedc"),
                            Address = "Rua Henrique Schaumann, 789",
                            Area = 120m,
                            Bathrooms = 3,
                            Bedrooms = 3,
                            City = "São Paulo",
                            CondoFee = 1300m,
                            CreatedAt = new DateTime(2026, 5, 27, 0, 30, 59, 508, DateTimeKind.Utc).AddTicks(6137),
                            Description = "Apartamento em andar alto, 3 dormitórios, sala ampla e excelente iluminação.",
                            ExternalId = "seed-004",
                            ImageUrl = "https://example.com/images/pinheiros.jpg",
                            Iptu = 260m,
                            IsActive = true,
                            IsFurnished = false,
                            IsPetFriendly = true,
                            LastSeenAt = new DateTime(2026, 5, 27, 0, 30, 59, 508, DateTimeKind.Utc).AddTicks(6136),
                            Neighborhood = "Pinheiros",
                            ParkingSpaces = 2,
                            Price = 2200000m,
                            PropertyType = "Apartment",
                            SourceName = "Viva Real",
                            SourceUrl = "https://www.vivareal.com.br/imovel/pinheiros",
                            Title = "Apartamento amplo em Pinheiros",
                            TransactionType = "Sale"
                        },
                        new
                        {
                            Id = new Guid("3e42bfa9-e55c-4e95-9f62-bcb0d986ace9"),
                            Address = "Rua Turiassu, 1550",
                            Area = 220m,
                            Bathrooms = 4,
                            Bedrooms = 4,
                            City = "São Paulo",
                            CondoFee = 2300m,
                            CreatedAt = new DateTime(2026, 5, 27, 0, 30, 59, 508, DateTimeKind.Utc).AddTicks(6156),
                            Description = "Cobertura com 4 dormitórios, terraço e área de lazer privativa.",
                            ExternalId = "seed-005",
                            ImageUrl = "https://example.com/images/perdizes.jpg",
                            Iptu = 520m,
                            IsActive = true,
                            IsFurnished = false,
                            IsPetFriendly = true,
                            LastSeenAt = new DateTime(2026, 5, 27, 0, 30, 59, 508, DateTimeKind.Utc).AddTicks(6144),
                            Neighborhood = "Perdizes",
                            ParkingSpaces = 3,
                            Price = 3980000m,
                            PropertyType = "Apartment",
                            SourceName = "Imovelweb",
                            SourceUrl = "https://www.imovelweb.com.br/imovel/perdizes",
                            Title = "Cobertura duplex em Perdizes",
                            TransactionType = "Sale"
                        },
                        new
                        {
                            Id = new Guid("6dc5f08e-c3bb-4469-8c2b-721891e6a7f2"),
                            Address = "Rua Itapura, 2150",
                            Area = 45m,
                            Bathrooms = 1,
                            Bedrooms = 1,
                            City = "São Paulo",
                            CondoFee = 620m,
                            CreatedAt = new DateTime(2026, 5, 27, 0, 30, 59, 508, DateTimeKind.Utc).AddTicks(6163),
                            Description = "Imóvel pronto para morar com 1 dormitório e varanda.",
                            ExternalId = "seed-006",
                            ImageUrl = "https://example.com/images/tatuape.jpg",
                            Iptu = 110m,
                            IsActive = true,
                            IsFurnished = false,
                            IsPetFriendly = false,
                            LastSeenAt = new DateTime(2026, 5, 27, 0, 30, 59, 508, DateTimeKind.Utc).AddTicks(6162),
                            Neighborhood = "Tatuapé",
                            ParkingSpaces = 1,
                            Price = 2600m,
                            PropertyType = "Apartment",
                            SourceName = "QuintoAndar",
                            SourceUrl = "https://www.quintoandar.com.br/imovel/tatuape",
                            Title = "Apartamento compacto em Tatuapé",
                            TransactionType = "Rent"
                        },
                        new
                        {
                            Id = new Guid("e0698619-918e-4ba7-bf3a-e755e3cdf1a0"),
                            Address = "Rua Lemos Monteiro, 220",
                            Area = 180m,
                            Bathrooms = 4,
                            Bedrooms = 3,
                            City = "São Paulo",
                            CondoFee = 0m,
                            CreatedAt = new DateTime(2026, 5, 27, 0, 30, 59, 508, DateTimeKind.Utc).AddTicks(6169),
                            Description = "Casa isolada com 3 suítes, piscina e jardim.",
                            ExternalId = "seed-007",
                            ImageUrl = "https://example.com/images/brooklin.jpg",
                            Iptu = 350m,
                            IsActive = true,
                            IsFurnished = false,
                            IsPetFriendly = true,
                            LastSeenAt = new DateTime(2026, 5, 27, 0, 30, 59, 508, DateTimeKind.Utc).AddTicks(6168),
                            Neighborhood = "Brooklin",
                            ParkingSpaces = 3,
                            Price = 2200000m,
                            PropertyType = "House",
                            SourceName = "Zap Imóveis",
                            SourceUrl = "https://www.zapimoveis.com.br/imovel/brooklin",
                            Title = "Casa com área gourmet no Brooklin",
                            TransactionType = "Sale"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
