// <auto-generated />
using System;
using BuscaImovel.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuscaImovel.Api.Data.Migrations
{
    [DbContext(typeof(BuscaImovelDbContext))]
    partial class BuscaImovelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.19");

            modelBuilder.Entity("BuscaImovel.Api.Entities.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Area")
                        .HasColumnType("TEXT");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CondoFee")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Iptu")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFurnished")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPetFriendly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ParkingSpaces")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("58b3e2d1-8a66-472f-ad60-133f7ce5ddd3"),
                            Address = "Avenida Ibirapuera, 1234",
                            Area = 68m,
                            Bathrooms = 2,
                            Bedrooms = 2,
                            City = "São Paulo",
                            CondoFee = 950m,
                            CreatedAt = new DateTime(2026, 5, 23, 20, 18, 20, 802, DateTimeKind.Utc).AddTicks(25),
                            Description = "Apartamento 2 dormitórios, mobiliado, composto por sala integrada, cozinha americana e varanda.",
                            ImageUrl = "https://example.com/images/moema.jpg",
                            Iptu = 180m,
                            IsFurnished = true,
                            IsPetFriendly = true,
                            Neighborhood = "Moema",
                            ParkingSpaces = 1,
                            Price = 5200m,
                            PropertyType = "Apartment",
                            SourceName = "QuintoAndar",
                            SourceUrl = "https://www.quintoandar.com.br/imovel/moema",
                            Title = "Apartamento mobiliado em Moema",
                            TransactionType = "Rent"
                        },
                        new
                        {
                            Id = new Guid("7694236c-46d0-4772-96d7-4fb5d9546295"),
                            Address = "Rua Sena Madureira, 987",
                            Area = 150m,
                            Bathrooms = 3,
                            Bedrooms = 3,
                            City = "São Paulo",
                            CondoFee = 0m,
                            CreatedAt = new DateTime(2026, 5, 23, 20, 18, 20, 802, DateTimeKind.Utc).AddTicks(40),
                            Description = "Casa térrea com 3 quartos, quintal e área gourmet próxima ao metrô.",
                            ImageUrl = "https://example.com/images/vila-mariana.jpg",
                            Iptu = 120m,
                            IsFurnished = false,
                            IsPetFriendly = true,
                            Neighborhood = "Vila Mariana",
                            ParkingSpaces = 2,
                            Price = 1450000m,
                            PropertyType = "House",
                            SourceName = "Zap Imóveis",
                            SourceUrl = "https://www.zapimoveis.com.br/imovel/vila-mariana",
                            Title = "House com quintal em Vila Mariana",
                            TransactionType = "Sale"
                        },
                        new
                        {
                            Id = new Guid("5ce729b8-aa32-46f8-8352-fc58eaa8b66e"),
                            Address = "Av. Cruzeiro do Sul, 3450",
                            Area = 32m,
                            Bathrooms = 1,
                            Bedrooms = 0,
                            City = "São Paulo",
                            CondoFee = 420m,
                            CreatedAt = new DateTime(2026, 5, 23, 20, 18, 20, 802, DateTimeKind.Utc).AddTicks(49),
                            Description = "Studio compacto com área de serviço, ideal para estudante ou jovem profissional.",
                            ImageUrl = "https://example.com/images/santana.jpg",
                            Iptu = 90m,
                            IsFurnished = true,
                            IsPetFriendly = false,
                            Neighborhood = "Santana",
                            ParkingSpaces = 0,
                            Price = 2200m,
                            PropertyType = "Studio",
                            SourceName = "OLX",
                            SourceUrl = "https://www.olx.com.br/imovel/santana",
                            Title = "Studio moderno em Santana",
                            TransactionType = "Rent"
                        },
                        new
                        {
                            Id = new Guid("04cf31a6-7367-4821-95a8-f29b1252c909"),
                            Address = "Rua Henrique Schaumann, 789",
                            Area = 120m,
                            Bathrooms = 3,
                            Bedrooms = 3,
                            City = "São Paulo",
                            CondoFee = 1300m,
                            CreatedAt = new DateTime(2026, 5, 23, 20, 18, 20, 802, DateTimeKind.Utc).AddTicks(59),
                            Description = "Apartamento em andar alto, 3 dormitórios, sala ampla e excelente iluminação.",
                            ImageUrl = "https://example.com/images/pinheiros.jpg",
                            Iptu = 260m,
                            IsFurnished = false,
                            IsPetFriendly = true,
                            Neighborhood = "Pinheiros",
                            ParkingSpaces = 2,
                            Price = 2200000m,
                            PropertyType = "Apartment",
                            SourceName = "Viva Real",
                            SourceUrl = "https://www.vivareal.com.br/imovel/pinheiros",
                            Title = "Apartamento amplo em Pinheiros",
                            TransactionType = "Sale"
                        },
                        new
                        {
                            Id = new Guid("55ebef17-9ff6-4b45-809b-c31c0c1bbad3"),
                            Address = "Rua Turiassu, 1550",
                            Area = 220m,
                            Bathrooms = 4,
                            Bedrooms = 4,
                            City = "São Paulo",
                            CondoFee = 2300m,
                            CreatedAt = new DateTime(2026, 5, 23, 20, 18, 20, 802, DateTimeKind.Utc).AddTicks(67),
                            Description = "Cobertura com 4 dormitórios, terraço e área de lazer privativa.",
                            ImageUrl = "https://example.com/images/perdizes.jpg",
                            Iptu = 520m,
                            IsFurnished = false,
                            IsPetFriendly = true,
                            Neighborhood = "Perdizes",
                            ParkingSpaces = 3,
                            Price = 3980000m,
                            PropertyType = "Apartment",
                            SourceName = "Imovelweb",
                            SourceUrl = "https://www.imovelweb.com.br/imovel/perdizes",
                            Title = "Cobertura duplex em Perdizes",
                            TransactionType = "Sale"
                        },
                        new
                        {
                            Id = new Guid("ea7a6bef-5dc2-40dd-9317-896f96642eab"),
                            Address = "Rua Itapura, 2150",
                            Area = 45m,
                            Bathrooms = 1,
                            Bedrooms = 1,
                            City = "São Paulo",
                            CondoFee = 620m,
                            CreatedAt = new DateTime(2026, 5, 23, 20, 18, 20, 802, DateTimeKind.Utc).AddTicks(76),
                            Description = "Imóvel pronto para morar com 1 dormitório e varanda.",
                            ImageUrl = "https://example.com/images/tatuape.jpg",
                            Iptu = 110m,
                            IsFurnished = false,
                            IsPetFriendly = false,
                            Neighborhood = "Tatuapé",
                            ParkingSpaces = 1,
                            Price = 2600m,
                            PropertyType = "Apartment",
                            SourceName = "QuintoAndar",
                            SourceUrl = "https://www.quintoandar.com.br/imovel/tatuape",
                            Title = "Apartamento compacto em Tatuapé",
                            TransactionType = "Rent"
                        },
                        new
                        {
                            Id = new Guid("3ecc7965-9194-4799-9746-51e8f3a7e2a0"),
                            Address = "Rua Lemos Monteiro, 220",
                            Area = 180m,
                            Bathrooms = 4,
                            Bedrooms = 3,
                            City = "São Paulo",
                            CondoFee = 0m,
                            CreatedAt = new DateTime(2026, 5, 23, 20, 18, 20, 802, DateTimeKind.Utc).AddTicks(101),
                            Description = "Casa isolada com 3 suítes, piscina e jardim.",
                            ImageUrl = "https://example.com/images/brooklin.jpg",
                            Iptu = 350m,
                            IsFurnished = false,
                            IsPetFriendly = true,
                            Neighborhood = "Brooklin",
                            ParkingSpaces = 3,
                            Price = 2200000m,
                            PropertyType = "House",
                            SourceName = "Zap Imóveis",
                            SourceUrl = "https://www.zapimoveis.com.br/imovel/brooklin",
                            Title = "Casa com área gourmet no Brooklin",
                            TransactionType = "Sale"
                        },
                        new
                        {
                            Id = new Guid("2b2c6278-2def-4095-9dd1-ecadaa9d31a7"),
                            Address = "Av. Corifeu de Azevedo Marques, 1120",
                            Area = 62m,
                            Bathrooms = 2,
                            Bedrooms = 2,
                            City = "São Paulo",
                            CondoFee = 540m,
                            CreatedAt = new DateTime(2026, 5, 23, 20, 18, 20, 802, DateTimeKind.Utc).AddTicks(110),
                            Description = "Apartamento com varanda, área de serviço, vaga de garagem e lazer completo.",
                            ImageUrl = "https://example.com/images/butanta.jpg",
                            Iptu = 130m,
                            IsFurnished = false,
                            IsPetFriendly = true,
                            Neighborhood = "Butantã",
                            ParkingSpaces = 1,
                            Price = 2900m,
                            PropertyType = "Apartment",
                            SourceName = "Imovelweb",
                            SourceUrl = "https://www.imovelweb.com.br/imovel/butanta",
                            Title = "Apartamento 2 quartos no Butantã",
                            TransactionType = "Rent"
                        },
                        new
                        {
                            Id = new Guid("832f1d2a-61f6-48e2-85f1-d15ebf99be0b"),
                            Address = "Rua da Saúde, 442",
                            Area = 28m,
                            Bathrooms = 1,
                            Bedrooms = 0,
                            City = "São Paulo",
                            CondoFee = 460m,
                            CreatedAt = new DateTime(2026, 5, 23, 20, 18, 20, 802, DateTimeKind.Utc).AddTicks(118),
                            Description = "Studio mobiliado com cozinha planejada e vista para a cidade.",
                            ImageUrl = "https://example.com/images/saude.jpg",
                            Iptu = 95m,
                            IsFurnished = true,
                            IsPetFriendly = false,
                            Neighborhood = "Saúde",
                            ParkingSpaces = 0,
                            Price = 2350m,
                            PropertyType = "Studio",
                            SourceName = "OLX",
                            SourceUrl = "https://www.olx.com.br/imovel/saude",
                            Title = "Studio próximo ao metrô Saúde",
                            TransactionType = "Rent"
                        },
                        new
                        {
                            Id = new Guid("de46cc1d-697d-4f0d-aab8-adbc8fda0ccf"),
                            Address = "Rua Domingos de Morais, 2050",
                            Area = 55m,
                            Bathrooms = 1,
                            Bedrooms = 1,
                            City = "São Paulo",
                            CondoFee = 750m,
                            CreatedAt = new DateTime(2026, 5, 23, 20, 18, 20, 802, DateTimeKind.Utc).AddTicks(127),
                            Description = "Apartamento 1 dormitório com cozinha americana e excelente localização.",
                            ImageUrl = "https://example.com/images/bela-vista.jpg",
                            Iptu = 210m,
                            IsFurnished = false,
                            IsPetFriendly = true,
                            Neighborhood = "Bela Vista",
                            ParkingSpaces = 1,
                            Price = 980000m,
                            PropertyType = "Apartment",
                            SourceName = "Viva Real",
                            SourceUrl = "https://www.vivareal.com.br/imovel/bela-vista",
                            Title = "Apartamento novo na Bela Vista",
                            TransactionType = "Sale"
                        },
                        new
                        {
                            Id = new Guid("d24c1608-9b71-4a44-a038-66a6467a2921"),
                            Address = "Rua da Mooca, 1020",
                            Area = 75m,
                            Bathrooms = 2,
                            Bedrooms = 2,
                            City = "São Paulo",
                            CondoFee = 780m,
                            CreatedAt = new DateTime(2026, 5, 23, 20, 18, 20, 802, DateTimeKind.Utc).AddTicks(136),
                            Description = "Apartamento 2 dormitórios, cozinha espaçosa e pronto para morar.",
                            ImageUrl = "https://example.com/images/mooca.jpg",
                            Iptu = 160m,
                            IsFurnished = false,
                            IsPetFriendly = true,
                            Neighborhood = "Mooca",
                            ParkingSpaces = 1,
                            Price = 3200m,
                            PropertyType = "Apartment",
                            SourceName = "QuintoAndar",
                            SourceUrl = "https://www.quintoandar.com.br/imovel/mooca",
                            Title = "Apartamento confortável na Mooca",
                            TransactionType = "Rent"
                        },
                        new
                        {
                            Id = new Guid("715d3a10-e142-4a9e-bd3f-7619beb06f84"),
                            Address = "Rua Serra de Bragança, 210",
                            Area = 140m,
                            Bathrooms = 3,
                            Bedrooms = 3,
                            City = "São Paulo",
                            CondoFee = 0m,
                            CreatedAt = new DateTime(2026, 5, 23, 20, 18, 20, 802, DateTimeKind.Utc).AddTicks(145),
                            Description = "Casa com 3 quartos, quintal e churrasqueira.",
                            ImageUrl = "https://example.com/images/tatuape-house.jpg",
                            Iptu = 280m,
                            IsFurnished = false,
                            IsPetFriendly = true,
                            Neighborhood = "Tatuapé",
                            ParkingSpaces = 2,
                            Price = 1850000m,
                            PropertyType = "House",
                            SourceName = "Imovelweb",
                            SourceUrl = "https://www.imovelweb.com.br/imovel/tatuape",
                            Title = "Casa em rua tranquila no Tatuapé",
                            TransactionType = "Sale"
                        },
                        new
                        {
                            Id = new Guid("225ca4b4-4cc6-4c95-b3b2-361336cfa14a"),
                            Address = "Avenida Sumaré, 500",
                            Area = 30m,
                            Bathrooms = 1,
                            Bedrooms = 0,
                            City = "São Paulo",
                            CondoFee = 520m,
                            CreatedAt = new DateTime(2026, 5, 23, 20, 18, 20, 802, DateTimeKind.Utc).AddTicks(155),
                            Description = "Studio com cozinha integrada e ótima localização.",
                            ImageUrl = "https://example.com/images/perdizes-studio.jpg",
                            Iptu = 105m,
                            IsFurnished = true,
                            IsPetFriendly = false,
                            Neighborhood = "Perdizes",
                            ParkingSpaces = 0,
                            Price = 2100m,
                            PropertyType = "Studio",
                            SourceName = "Zap Imóveis",
                            SourceUrl = "https://www.zapimoveis.com.br/imovel/perdizes",
                            Title = "Apartamento studio em Perdizes",
                            TransactionType = "Rent"
                        },
                        new
                        {
                            Id = new Guid("1aae2288-30a2-4162-bea9-e316c70db978"),
                            Address = "Rua do Rocio, 1600",
                            Area = 110m,
                            Bathrooms = 3,
                            Bedrooms = 2,
                            City = "São Paulo",
                            CondoFee = 1400m,
                            CreatedAt = new DateTime(2026, 5, 23, 20, 18, 20, 802, DateTimeKind.Utc).AddTicks(164),
                            Description = "2 dormitórios com varanda e lazer completo.",
                            ImageUrl = "https://example.com/images/brooklin-sale.jpg",
                            Iptu = 310m,
                            IsFurnished = false,
                            IsPetFriendly = true,
                            Neighborhood = "Brooklin",
                            ParkingSpaces = 2,
                            Price = 2550000m,
                            PropertyType = "Apartment",
                            SourceName = "OLX",
                            SourceUrl = "https://www.olx.com.br/imovel/brooklin",
                            Title = "Apartamento com vista no Brooklin",
                            TransactionType = "Sale"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
